
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LIBRARY COMMAND PARAMETERstatement : statement_parseCommandstatement_parseCommand : LIBRARY COMMAND PARAMETER'
    
_lr_action_items = {'LIBRARY':([0,],[3,]),'$end':([1,2,5,],[0,-1,-2,]),'COMMAND':([3,],[4,]),'PARAMETER':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'statement_parseCommand':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> statement_parseCommand','statement',1,'p_statement','timeParser.py',10),
  ('statement_parseCommand -> LIBRARY COMMAND PARAMETER','statement_parseCommand',3,'p_statement_parseCommand','timeParser.py',16),
]
